# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
  config.vm.synced_folder "../environments", "/salt"

    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize any other parameters
    vb.customize [
     'modifyvm',                :id,
     '--memory',                '2048',
     '--cpus',                  '4',
     '--paravirtprovider',      'kvm', # can be set to "paravirt", fast on linux (kernel virtual machine)
     '--ioapic',                'on', # turn on I/O APIC
     '--natdnsproxy1',          'on',
     '--uartmode1',             'disconnected', # disable ugly log cloudimg-consol.log file
     '--natdnshostresolver1',   'on']
    end


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.define "salt" do |web|
    web.vm.hostname = "salt.vagrant"
    web.vm.network "private_network", ip: "192.168.10.10"

    web.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "../config/minion_conf.yml"
      salt.run_highstate = true
      salt.verbose = false
      end
    end
  end
