file_client: local
master_type: disable
state_output: mixed
default_top: base


env_order:
  - base
  - dev

file_roots:
  base:
    - /salt/base/states
  dev:
    - /salt/base/states

pillar_roots:
  base:
    - /salt/base/pillars
  dev:
    - /salt/base/pillars
